# Generated by Django 3.1.12 on 2023-08-01 15:31

from django.db import migrations, models
import djongo.models.fields
import server.apps.bubbles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttachBubbleEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachBubble', djongo.models.fields.EmbeddedField(model_container=server.apps.bubbles.models.AttachBubble)),
            ],
        ),
        migrations.CreateModel(
            name='BubbleEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bubble', djongo.models.fields.EmbeddedField(model_container=server.apps.bubbles.models.Bubble)),
            ],
        ),
    ]
