# Generated by Django 4.2.4 on 2023-08-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubbles', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blindbubble',
            name='is_notice',
            field=models.IntegerField(choices=[(0, 'CHAT'), (1, 'NOTICE')], default=0),
        ),
        migrations.AddField(
            model_name='bubble',
            name='is_notice',
            field=models.IntegerField(choices=[(0, 'CHAT'), (1, 'NOTICE')], default=0),
        ),
    ]
