# Generated by Django 4.2.4 on 2023-08-21 21:27

from django.db import migrations, models
import server.apps.channels.models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='default_image',
            field=models.ImageField(blank=True, default='default_profile/default_profile.png', upload_to=server.apps.channels.models.Channel.upload_to_func),
        ),
    ]
