# Generated by Django 3.1.12 on 2023-08-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_auto_20230803_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='default_image',
            field=models.ImageField(blank=True, default='static/image/default_profile/default_profile.png', upload_to='channels/%Y%m%d'),
        ),
    ]
