# Generated by Django 3.1.12 on 2023-08-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0006_auto_20230805_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='default_image',
        ),
    ]
