# Generated by Django 3.1.12 on 2023-08-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0008_channel_default_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_ok',
            field=models.IntegerField(default=0),
        ),
    ]
