# Generated by Django 4.1.10 on 2023-08-11 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0010_auto_20230807_1856'),
        ('channels', '0010_auto_20230807_1858'),
        ('channels', '0011_alter_channel_id_alter_join_id_alter_passer_id_and_more'),
    ]

    operations = [
    ]
