# Generated by Django 4.2.4 on 2023-08-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0012_alter_channel_id_alter_join_id_alter_passer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_ok',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'YES')], default=0),
        ),
    ]
