# Generated by Django 4.2.4 on 2023-08-13 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0012_merge_20230811_1508'),
        ('channels', '0013_alter_channel_channel_ok'),
    ]

    operations = [
    ]
