# Generated by Django 4.2.4 on 2023-12-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openchat',
            name='b',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openchat',
            name='g',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openchat',
            name='r',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
