# Generated by Django 4.2.4 on 2023-12-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_openchat_b_openchat_g_openchat_r'),
    ]

    operations = [
        migrations.AddField(
            model_name='openpost',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='openpost',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='openpost',
            name='sad',
            field=models.IntegerField(default=0),
        ),
    ]
