# Generated by Django 4.2.4 on 2023-08-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blindroommember',
            name='profile_img',
            field=models.CharField(max_length=200),
        ),
    ]
