# Generated by Django 4.2.4 on 2023-08-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_blindroommember_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blindroommember',
            name='profile_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
