# Generated by Django 4.1.10 on 2023-08-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_blindroommember_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blindroommember',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='20230820'),
        ),
    ]
