# Generated by Django 4.2.4 on 2023-08-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20230807_1856'),
        ('chat', '0004_auto_20230807_1858'),
        ('chat', '0005_auto_20230807_2128'),
    ]

    operations = [
    ]
