# Generated by Django 4.2.4 on 2023-08-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_blindroommember_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_img',
            field=models.ImageField(default='default_profile/default_profile.png', upload_to='20230821'),
        ),
        migrations.AlterField(
            model_name='blindroommember',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='20230821'),
        ),
    ]
