# Generated by Django 4.2.4 on 2023-08-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_room_room_img_alter_blindroommember_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blindroommember',
            name='is_room_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roommember',
            name='is_room_owner',
            field=models.BooleanField(default=False),
        ),
    ]
