# Generated by Django 4.1.10 on 2023-08-11 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20230807_1856'),
        ('chat', '0004_auto_20230807_1858'),
        ('chat', '0006_alter_blindroommember_id_alter_lock_id_alter_room_id_and_more'),
    ]

    operations = [
    ]
