# Generated by Django 4.2.4 on 2023-08-13 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_blindroommember_id_alter_lock_id_alter_room_id_and_more'),
        ('chat', '0007_merge_20230811_1508'),
    ]

    operations = [
    ]
