# Generated by Django 4.2.4 on 2023-08-21 21:27

from django.db import migrations, models
import server.apps.chat.models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_blindroommember_is_room_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_img',
            field=models.ImageField(blank=True, default='default_profile/default_profile.png', upload_to=server.apps.chat.models.Room.upload_to_func),
        ),
    ]
