# Generated by Django 4.2.4 on 2023-08-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_room_room_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blindroommember',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='20230822'),
        ),
    ]
