# Generated by Django 4.2.4 on 2023-12-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_blindroommember_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blindroommember',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='20231203'),
        ),
    ]
