# Generated by Django 4.1.10 on 2023-08-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local_users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Join',
        ),
    ]
