# Generated by Django 4.2.3 on 2023-08-02 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local_users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Join',
        ),
    ]
