# Generated by Django 4.2.4 on 2023-08-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, default='default_profile/default_profile.png', null=True, upload_to='posts/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(default='lightMode', max_length=16),
        ),
    ]
