# Generated by Django 3.1.12 on 2023-08-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_users', '0002_delete_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
