# Generated by Django 3.1.12 on 2023-08-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_users', '0003_auto_20230803_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(default='#ffffff', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='posts/%Y%m%d'),
        ),
    ]
