# Generated by Django 4.2.4 on 2023-08-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_users', '0004_auto_20230803_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.CharField(max_length=13, verbose_name='휴대폰 번호')),
                ('auth_num', models.CharField(max_length=13, verbose_name='인증번호')),
            ],
            options={
                'verbose_name_plural': '휴대폰인증 관리 페이지',
                'db_table': 'authentications',
            },
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
