# Generated by Django 4.2.4 on 2023-08-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local_users', '0005_auth_alter_bookmark_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auth',
            new_name='SMS_Auth',
        ),
    ]
