# Generated by Django 4.2.4 on 2023-08-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local_users', '0005_auto_20230807_1838'),
        ('local_users', '0005_auto_20230807_1856'),
        ('local_users', '0005_auto_20230807_1858'),
    ]

    operations = [
    ]
