# Generated by Django 4.1.10 on 2023-08-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_users', '0006_alter_bookmark_id_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS_Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.CharField(max_length=13, verbose_name='휴대폰 번호')),
                ('auth_num', models.CharField(max_length=13, verbose_name='인증번호')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
