# Generated by Django 4.1.10 on 2023-08-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_users', '0007_sms_auth_remove_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
