# Generated by Django 4.2.4 on 2023-08-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_users', '0007_alter_user_id_delete_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS_Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.CharField(max_length=20, verbose_name='휴대폰 번호')),
                ('auth_num', models.CharField(max_length=10, null=True, verbose_name='인증번호')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
