# Generated by Django 4.1.10 on 2023-08-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_users', '0008_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms_auth',
            name='auth_num',
            field=models.CharField(max_length=10, null=True, verbose_name='인증번호'),
        ),
        migrations.AlterField(
            model_name='sms_auth',
            name='phone_num',
            field=models.CharField(max_length=20, verbose_name='휴대폰 번호'),
        ),
    ]
