# Generated by Django 4.1.10 on 2023-08-11 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local_users', '0005_auto_20230807_1856'),
        ('local_users', '0005_auto_20230807_1858'),
        ('local_users', '0009_alter_sms_auth_auth_num_alter_sms_auth_phone_num'),
    ]

    operations = [
    ]
