# Generated by Django 4.2.4 on 2023-08-13 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local_users', '0008_sms_auth_alter_user_phone_number'),
        ('local_users', '0010_merge_20230811_1508'),
    ]

    operations = [
    ]
